### ISSUE TITLE
im having a problem initializing the webdriver

### ISSUE THREAD

**Issue by JeromeRadlach** [arthur-alves/sunflower-farmers-automated-bot#2]
```
S = Service(ChromeDriverManager().install())
DRIVER = webdriver.Chrome(service=S, options=OPTIONS)
```

it looks like while installing the chromedriver the service object does not insert the chromedriver binary into PATH.
```

 [STARTING SUNFLOWER FARMERS AUTOMATED BOT...] 

 initializing webdriver


====== WebDriver manager ======
Current google-chrome version is 97.0.4692
Get LATEST chromedriver version for 97.0.4692 google-chrome
Driver [C:\Users\Jerom\.wdm\drivers\chromedriver\win32\97.0.4692.71\chromedriver.exe] found in cache

DevTools listening on ws://127.0.0.1:50017/devtools/browser/eb713226-4324-4925-870d-1777768a0631
[6616:10628:0106/161010.843:ERROR:chrome_browser_main_extra_parts_metrics.cc(227)] START: ReportBluetoothAvailability(). If you don't see the END: message, this is crbug.com/1216328.
[6616:12148:0106/161010.843:ERROR:device_event_log_impl.cc(214)] [16:10:10.848] USB: usb_device_handle_win.cc:1050 Failed to read descriptor from 
node connection: Ein an das System angeschlossenes Gerõt funktioniert nicht. (0x1F)
[6616:12148:0106/161010.851:ERROR:device_event_log_impl.cc(214)] [16:10:10.852] USB: usb_device_handle_win.cc:1050 Failed to read descriptor from 
node connection: Ein an das System angeschlossenes Gerõt funktioniert nicht. (0x1F)
[6616:10628:0106/161010.855:ERROR:chrome_browser_main_extra_parts_metrics.cc(230)] END: ReportBluetoothAvailability()
[6616:10628:0106/161010.862:ERROR:chrome_browser_main_extra_parts_metrics.cc(235)] START: GetDefaultBrowser(). If you don't see the END: message, 
this is crbug.com/1216328.
[6616:10628:0106/161010.879:ERROR:chrome_browser_main_extra_parts_metrics.cc(239)] END: GetDefaultBrowser()
Traceback (most recent call last):
  File "C:\Users\Jerom\Desktop\Dev\sunflower-farmers-automated-bot\main.py", line 25, in <module>
    DRIVER = webdriver.Chrome(service=S, options=OPTIONS)
  File "C:\Users\Jerom\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__    
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\Jerom\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 93, in __init__  
    RemoteWebDriver.__init__(
  File "C:\Users\Jerom\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 268, in __init__   
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Jerom\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 359, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Jerom\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute    
    self.error_handler.check_response(response)
  File "C:\Users\Jerom\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: failed to wait for extension background page to load: chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.html
from timeout: Timed out receiving message from renderer: 10.000
Stacktrace:
Backtrace:
        Ordinal0 [0x00E5FDC3+2555331]
        Ordinal0 [0x00DF77F1+2127857]
        Ordinal0 [0x00CF2E08+1060360]
        Ordinal0 [0x00CE53A8+1004456]
        Ordinal0 [0x00CE43FA+1000442]
        Ordinal0 [0x00CE47C7+1001415]
        Ordinal0 [0x00CEE4FF+1041663]
        Ordinal0 [0x00CF884B+1083467]
        Ordinal0 [0x00CFAF60+1093472]
        Ordinal0 [0x00CE4AC6+1002182]
        Ordinal0 [0x00CF84B8+1082552]
        Ordinal0 [0x00CDA970+960880]
        Ordinal0 [0x00D0E3DF+1172447]
        Ordinal0 [0x00D0AFC1+1159105]
        Ordinal0 [0x00D3C22F+1360431]
        Ordinal0 [0x00D3BE9A+1359514]
        Ordinal0 [0x00D37976+1341814]
        Ordinal0 [0x00D136B6+1193654]
        Ordinal0 [0x00D14546+1197382]
        GetHandleVerifier [0x00FF9622+1619522]
        GetHandleVerifier [0x010A882C+2336844]
        GetHandleVerifier [0x00EF23E1+541697]
        GetHandleVerifier [0x00EF1443+537699]
        Ordinal0 [0x00DFD18E+2150798]
        Ordinal0 [0x00E01518+2168088]
        Ordinal0 [0x00E01660+2168416]
        Ordinal0 [0x00E0B330+2208560]
        BaseThreadInitThunk [0x759EFA29+25]
        RtlGetAppContainerNamedObjectPath [0x77607A9E+286]
        RtlGetAppContainerNamedObjectPath [0x77607A6E+238]
```

**Comment by arthur-alves** [comment]
Hey @JeromeRadlach !!

I saw that is a common issue for chrome driver in the community, so with that I did not found a real solution, but I made a small fix that can deal with the problem, trying to restart the driver sometimes. I was able to reproduce the same problem, and with this new solution works, can you try please?

Update your project and try again please.

Let me know if you need something

**Comment by Blek182** [comment]
> Hey @JeromeRadlach !!
> 
> I saw that is a common issue for chrome driver in the community, so with that I did not found a real solution, but I made a small fix that can deal with the problem, trying to restart the driver sometimes. I was able to reproduce the same problem, and with this new solution works, can you try please?
> 
> Update your project and try again please.
> 
> Let me know if you need something

I think i face the same problem? What should i do then?


```
[STARTING SUNFLOWER FARMERS AUTOMATED BOT...]



====== WebDriver manager ======
Current google-chrome version is 97.0.4692
Get LATEST chromedriver version for 97.0.4692 google-chrome
Driver [C:\Users\Admin\.wdm\drivers\chromedriver\win32\97.0.4692.71\chromedriver.exe] found in cache
DevTools listening on ws://127.0.0.1:55762/devtools/browser/66d9bb3e-5597-4be8-9bd2-d5e6b3b8189a
[4092:1536:0107/035435.065:ERROR:chrome_browser_main_extra_parts_metrics.cc(227)] START: ReportBluetoothAvailability(). If you don't see the END: message, this is crbug.com/1216328.
[4092:1536:0107/035435.078:ERROR:chrome_browser_main_extra_parts_metrics.cc(230)] END: ReportBluetoothAvailability()
[4092:2228:0107/035435.078:ERROR:device_event_log_impl.cc(214)] [03:54:35.076] Bluetooth: bluetooth_adapter_winrt.cc:1075 Getting Default Adapter failed.
[4092:1536:0107/035435.111:ERROR:chrome_browser_main_extra_parts_metrics.cc(235)] START: GetDefaultBrowser(). If you don't see the END: message, this is crbug.com/1216328.
[4092:1536:0107/035435.125:ERROR:chrome_browser_main_extra_parts_metrics.cc(239)] END: GetDefaultBrowser()
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\sunflower-farmers-automated-bot-master-2\main.py", line 331, in setup_driver
    DRIVER = webdriver.Chrome(service=S, options=OPTIONS)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 268, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 359, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: failed to wait for extension background page to load: chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.html
from timeout: Timed out receiving message from renderer: 10.000
Stacktrace:
Backtrace:
        Ordinal0 [0x008BFDC3+2555331]
        Ordinal0 [0x008577F1+2127857]
        Ordinal0 [0x00752E08+1060360]
        Ordinal0 [0x007453A8+1004456]
        Ordinal0 [0x007443FA+1000442]
        Ordinal0 [0x007447C7+1001415]
        Ordinal0 [0x0074E4FF+1041663]
        Ordinal0 [0x0075884B+1083467]
        Ordinal0 [0x0075AF60+1093472]
        Ordinal0 [0x00744AC6+1002182]
        Ordinal0 [0x007584B8+1082552]
        Ordinal0 [0x0073A970+960880]
        Ordinal0 [0x0076E3DF+1172447]
        Ordinal0 [0x0076AFC1+1159105]
        Ordinal0 [0x0079C22F+1360431]
        Ordinal0 [0x0079BE9A+1359514]
        Ordinal0 [0x00797976+1341814]
        Ordinal0 [0x007736B6+1193654]
        Ordinal0 [0x00774546+1197382]
        GetHandleVerifier [0x00A59622+1619522]
        GetHandleVerifier [0x00B0882C+2336844]
        GetHandleVerifier [0x009523E1+541697]
        GetHandleVerifier [0x00951443+537699]
        Ordinal0 [0x0085D18E+2150798]
        Ordinal0 [0x00861518+2168088]
        Ordinal0 [0x00861660+2168416]
        Ordinal0 [0x0086B330+2208560]
        BaseThreadInitThunk [0x7623FA29+25]
        RtlGetAppContainerNamedObjectPath [0x76F27A9E+286]
        RtlGetAppContainerNamedObjectPath [0x76F27A6E+238]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\sunflower-farmers-automated-bot-master-2\main.py", line 372, in <module>
    main()
  File "C:\Users\Admin\Desktop\sunflower-farmers-automated-bot-master-2\main.py", line 352, in main
    setup_driver()
  File "C:\Users\Admin\Desktop\sunflower-farmers-automated-bot-master-2\main.py", line 334, in setup_driver
    raise ValueError('Was not possible to mount driver.')
ValueError: Was not possible to mount driver.
```

**Comment by 17ss** [comment]
10 seconds are a bit small for your host.
`WebDriver.set_page_load_timeout(100)`
