### ISSUE TITLE
Multiple account issue

### ISSUE THREAD

**Issue by awaping** [arthur-alves/sunflower-farmers-automated-bot#4]
Hey mate,

First of all thank you for your work, this is great !
I have an issue when I try to use multiple account feature, the I use it like that:
```
use_multi_acc: true
 multi_acc_list:
   - [my secret phrase1, mypasswd1, sunflower]
   - [my secret phrase2, mypasswd2, sunflower]
   - [my secret phrase3, mypasswd3, sunflower]
   - [my secret phrase4, mypasswd4, sunflower]
```
I try without the "-", I try a lot of things but I got this Traceback:
```
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from settings import settings, plants_type
  File "/home/sf/settings.py", line 15, in <module>
    settings = get_config()
  File "/home/sf/settings.py", line 11, in get_config
    raise ValueError(
ValueError: Something goes wrong with you config file. Please check config.yaml file.

```

I am on Ubuntu 20.04.3 LTS and also try on Windows but when I start main.py the cmd get instant closed and nothing happen (but works with one account).

Thank you again for your work, and thank you for your answer.
Tom

**Comment by arthur-alves** [comment]
The server is now offline, so I can't test to solve the problem, sorry. If the game opens again I'll take it back.

**Comment by awaping** [comment]
> The server is now offline, so I can't test to solve the problem, sorry. If the game opens again I'll take it back.

No problem bro, thank you for the answer.
